# Generated by Django 4.0.5 on 2022-07-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameoverflow', '0004_rename_answer_question_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.IntegerField(default=0),
        ),
    ]
